#Режим игры (NORMAL - обычная игра, RANKED - рейтинговая игра)
mode: RANKED

#Мир, где будет проходить игра
world: world

#Местоположение, где будут появляться игроки при заходе в игру
lobby: 0.5, 62, 0.5, 130, 0

#Название карты
name: Тест

#Количество игроков на каждом острове
islandPlayers: 1

#Высота на которой будут появляться зрители
respawnY: 70

#Местоположения обычных сундуков
basicChests:
  - 201, 68, 312
  - 182, 70, 301

#Местоположения центральных сундуков
middleChests:
  - 200, 75, 291
  - 190, 74, 283

#Местоположение мистического сундука
mysteryChest: 202, 72, 280

#Местоположения, где игроки будут появляться через 20 минут после начала игры (DeathMatch)
deathmatchSpawns:
  - 218.5, 80.2, 281.5
  - 216.5, 79.2, 284.5

#Местоположения спавна и сундуков острова
islands:
  -
    spawn: 220.5, 80.2, 329.5
    chests:
      - 222, 79, 330
      - 220, 75, 329
      - 217, 75, 332
  -
    spawn: 239.5, 80.2, 317.5
    chests:
      - 241, 79, 318
      - 239, 75, 317
      - 236, 75, 320